services:
  todo-app:
    image: lhatmjnk/license_plate_verify-todo-app:latest
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
    develop:
      watch:
        - path: .
          action: rebuild
        - path: .
          target: /usr/src/app
          action: sync

  db:
    image: lhatmjnk/db:latest
    restart: always
    environment:
      POSTGRES_DB: LP_Verification
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 177013
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./App/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
